
-- PROCCI
create PROC PANKKI.LisaaAsiakas
--PROCIN PARAMETRIT
@etunimi varchar(200) = NULL,
@sukunimi varchar(200) = NULL
AS
--PROCIN MUUTTUJAT
 SET NOCOUNT ON
DECLARE
 @TAPAHTUMACHECK INT
 SET @TAPAHTUMACHECK = @@TRANCOUNT 
 --JOS OLLAAN TAPAHTUMAN SISÄLLÄ, SAVE
 IF @TAPAHTUMACHECK > 0
	SAVE TRAN PROCSAVE
 --MUUTION ALOITETAAN TAPAHTUMA
 ELSE
	BEGIN TRAN
 BEGIN TRY
 --EI ANNETTU MITÄÄN PARAMETREJA
 IF @ETUNIMI IS NULL AND @SUKUNIMI IS NULL
 BEGIN
 RAISERROR('ANNAPPA VÄHINTÄÄN YKSI NIMI',11,1)
 END
 --YRITYSASIAKAS
 IF @etunimi IS NOT NULL AND @sukunimi IS NULL
  EXEC PANKKI.LisaaYritysAsiakas @etunimi
  --MUUTOIN KUTSTUTAAN LisaaHenkiloAsiakas
 if @Etunimi IS NOT NULL AND @sukunimi IS NOT NULL
  EXEC PANKKI.LisaaHenkiloAsiakas @etunimi,@sukunimi

  --jos ei ollu tapahtumaa, committi
  if @TAPAHTUMACHECK = 0
  commit
 --CATCH
  END TRY
 BEGIN CATCH
    DECLARE @virhe NVARCHAR(4000)
    SELECT @virhe = ERROR_MESSAGE()

	IF @TAPAHTUMACHECK = 0
	 ROLLBACK

    ELSE 
	BEGIN
    IF XACT_STATE() <> -1
      ROLLBACK TRAN PROCSAVE
    END

    RAISERROR(@virhe,11,1)
 END CATCH
 SET NOCOUNT OFF
 GO

 

 --HENKILÖN LISÄYS
 CREATE PROC PANKKI.LisaaHenkiloAsiakas
 @ETUNIMI VARCHAR(200),
 @SUKUNIMI VARCHAR(200)

 AS
 SET NOCOUNT ON
 DECLARE @ASIAKASID INT,
 @TAPAHTUMACHECK INT
 SET @TAPAHTUMACHECK = @@TRANCOUNT
--JOS OLLAAN TAPAHTUMAN SISÄLLÄ, SAVE
 IF @TAPAHTUMACHECK > 0
	SAVE TRAN PROCSAVE
 --MUUTION ALOITETAAN TAPAHTUMA
 ELSE
	BEGIN TRAN
 BEGIN TRY

 INSERT INTO pankki.asiakas DEFAULT VALUES
 SET @asiakasid = @@IDENTITY --edellä lisätyn rivin sisältämä id
 --
 INSERT INTO pankki.henkilo (id, etunimi, sukunimi)
 VALUES (@asiakasid, @etunimi, @sukunimi) 

  --jos ei ollu tapahtumaa, committi
  if @TAPAHTUMACHECK =0
  commit
  PRINT'ASIAKAS LISÄTTIIN'
  --CATCH
 END TRY
 BEGIN CATCH
  DECLARE @virhe NVARCHAR(4000)
    SELECT @virhe = ERROR_MESSAGE()
	--JOS OLTIIN JO TAPAHTUMAN SISÄLLÄ, ROLLBACKATAAN SAVEPOINTTIIN
    IF XACT_STATE() <> 0
	 BEGIN
      ROLLBACK TRAN PROCSAVE
    END
    RAISERROR(@virhe,11,1)
 END CATCH

 SET NOCOUNT OFF
 GO


 --YRITYSASIAKAS
 CREATE PROC PANKKI.LisaaYritysAsiakas
 @NIMI VARCHAR(200)
 AS
 SET NOCOUNT ON
 DECLARE @ASIAKASID INT,
 @TAPAHTUMACHECK INT
 SET @TAPAHTUMACHECK = @@TRANCOUNT
 --JOS OLLAAN TAPAHTUMAN SISÄLLÄ, SAVE
  IF @TAPAHTUMACHECK > 0
	SAVE TRAN PROCSAVE
 --MUUTION ALOITETAAN TAPAHTUMA
 ELSE
	BEGIN TRAN
 BEGIN TRY

 INSERT INTO pankki.asiakas DEFAULT VALUES 
 SET @ASIAKASID = @@IDENTITY

 INSERT INTO PANKKI.YRITYS(NIMI, ID)
 VALUES (@NIMI, @ASIAKASID)
  --jos ei ollu tapahtumaa, committi
  if @TAPAHTUMACHECK =0
  commit
   PRINT'ASIAKAS LISÄTTIIN'
   --CATCH
 END TRY
 BEGIN CATCH
  DECLARE @virhe NVARCHAR(4000)
    SELECT @virhe = ERROR_MESSAGE()
    IF XACT_STATE() <> 0
	 BEGIN
      ROLLBACK TRAN PROCSAVE
    END
    RAISERROR(@virhe,11,1)
 END CATCH

 SET NOCOUNT OFF
 GO


 EXEC PANKKI.LISAAASIAKAS 'MATTI'
 EXEC PANKKI.LISAAASIAKAS 'MATTI', 'MEIKÄLÄINEN'
 EXEC PANKKI.LISAAASIAKAS
