CREATE FUNCTION PANKKI.AsiakasNimiId(
@ID INT)
RETURNS VARCHAR(200)
AS
BEGIN
DECLARE @NIMI VARCHAR(200)
--JOS IDN OMAAVIA HENKILÖITÄ LÖYTYY
IF (SELECT COUNT(ID) FROM PANKKI.HENKILO WHERE ID = @ID) !=0
BEGIN
SET @NIMI = (SELECT ETUNIMI +' '+ SUKUNIMI AS NIMI
FROM PANKKI.HENKILO
WHERE ID = @ID)
END
--JOS LÖYTYY IDN OMAAVIA YRITYKSIÄ
IF (SELECT COUNT(ID) FROM PANKKI.YRITYS  WHERE ID = @ID) !=0
BEGIN
SET @NIMI = (SELECT NIMI FROM PANKKI.YRITYS WHERE ID = @ID)
END
RETURN @NIMI

END
GO

--SELECT PANKKI.ASIAKASNIMIID(166)
--SELECT PANKKI.ASIAKASNIMIID(276)

GO

SELECT*
FROM PANKKI.HENKILO

SELECT*
FROM PANKKI.YRITYS
GO

CREATE FUNCTION PANKKI.AsiakasNimiTili(
@TILINUMERO VARCHAR(200)
)
RETURNS VARCHAR(200)
AS
BEGIN
DECLARE @NIMI VARCHAR(200),
@ID BIGINT
--JOS LÖYTYY TILINUMEROLLE OMISTAJA
SET @ID = (SELECT TOP 1 OMISTAJA FROM PANKKI.TILI WHERE  CD =@TILINUMERO)
IF @ID IS NOT NULL

BEGIN
	IF (SELECT COUNT(ID) FROM PANKKI.HENKILO WHERE ID = @ID) !=0
	BEGIN
	SET @NIMI = (SELECT ETUNIMI +' '+ SUKUNIMI AS NIMI
	FROM PANKKI.HENKILO
	WHERE ID = @ID)
	END

	ELSE
	BEGIN
	SET @NIMI = (SELECT NIMI FROM PANKKI.YRITYS WHERE ID = @ID)
END
END
RETURN @NIMI
END 
GO

--SELECT PANKKI.ASIAKASNIMITILI('123456-124239')

--SELECT*
--FROM PANKKI.TILI

--SELECT*
--FROM PANKKI.YRITYS