--T1
SELECt X.LUOKKA, A.sukunimi

FROM HENKILO AS a
			CROSS APPLY	(
SELECt B.sukunimi,
CASE
WHEN PALKKA BETWEEN 0 AND 4999 THEN '0-4999'
WHEN PALKKA BETWEEN 5000 AND 5999 THEN '5000-5999'
WHEN PALKKA BETWEEN 6000 AND 9999 THEN '6000- 99999'

END AS LUOKKA

FROM HENKILO AS B
WHERE B.SUKUNIMI = A.SUKUNIMI ) AS X
ORDER BY LUOKKA, SUKUNIMI

--T2

SELECT TOP 1 C.POSTITP, SUM(D.MAARA*E.YKSHINTA) AS 'SUMMA'
FROM HENKILO AS A 
JOIN dbo.TILOTS AS B ON B.HLOTUN = A.HLOTUN
JOIN ASIAKAS AS C ON C.ASNRO = B.ASNRO
JOIN TILRIV AS D ON D.TILNRO = B.TILNRO
JOIN VARASTO AS E ON E.TUOTEKDI = D.TUOTEKDI
GROUP BY C.POSTITP
ORDER BY SUMMA DESC



--t3
SELECT *
FROM( SELECT b.POSTITP,c.kaupunki
FROM TILOTS AS A 
JOIN ASIAKAS AS B ON B.ASNRO = A.ASNRO
JOIN HENKILO AS C ON C.HLOTUN = A.HLOTUN

) AS BM
PIVOT(COUNT(kaupunki)
FOR kaupunki IN ([helsinki], [tampere], [turku]))AS x


--t4
SELECT DISTINCT A.TILNRO,FORMAT( A.TILAUSPV,'dd.MM.yyyy')
FROM dbo.TILOTS AS A
WHERE NOT EXISTS
		(SELECT 1
		FROM dbo.OSAT AS B
		WHERE EXISTS
				(SELECT *
				FROM TILRIV AS C
				WHERE C.TILNRO = 20003
				AND C.TUOTEKDI = B.TUOTEKDI)
		AND NOT EXISTS(SELECT 1 
					  FROM TILRIV AS D
					  WHERE D.TUOTEKDI = B.TUOTEKDI
					  AND D.TILNRO = A.TILNRO))


--T5 ??
SELECT A.ESIMIES AS ESIMIESID ,a.HLOTUN AS HENKILOID , CONCAT(A.ETUNIMI , ' ' , A.SUKUNIMI) AS NIMI,
CASE WHEN A.ESIMIES IS NULL THEN 0
ELSE 1
END AS	LEVEL
FROM HENKILO AS A
ORDER BY LEVEL, ESIMIESID, NIMI

--T5

WITH TASOT (ESIMIESID, HENKILOID, NIMI, LEVEL) AS(
SELECT A.ESIMIES,a.HLOTUN, CONCAT(A.ETUNIMI , ' ' , A.SUKUNIMI) AS NIMI,
CASE WHEN A.ESIMIES IS NULL THEN 0
ELSE 1
END AS	LEVEL
FROM HENKILO AS A

)
SELECT ESIMIESID,HENKILOID, NIMI, LEVEL
FROM TASOT
ORDER BY LEVEL, ESIMIESID, NIMI



		