DECLARE 
@KOKO INT = 23,
@DEC DECIMAL(5,2) = 3.89,
@STRI NCHAR(5) = 'VIISI',
@STRIN NVARCHAR(20) = 'PETTERI PUNAKUONO',
@PVM DATE = GETDATE(),
@AIKA DATETIME = '2011.09.01 13:40'--CURRENT_TIMESTAMP,


BEGIN
SET @KOKO =@KOKO*3
SET @DEC +=1.0

SELECT @STRI AS STRI, @DEC AS DEC, @KOKO AS KOKO, @STRIN AS STRIN, @PVM AS PVM,@AIKA AS AIKA
END
GO

--T2
DECLARE @TAULU TABLE(LUKUID INT, KAYTETTY BIT)
DECLARE @I INT= 7
DECLARE @VAPAAT INT
BEGIN
	INSERT INTO @TAULU VALUES (1, 0)
	INSERT INTO @TAULU VALUES (2, 0)
	INSERT INTO @TAULU VALUES (3, 0)
	INSERT INTO @TAULU VALUES (4, 0)
	INSERT INTO @TAULU VALUES (5, 0)
	INSERT INTO @TAULU VALUES (6, 0)

	UPDATE @TAULU
	SET KAYTETTY=1
	WHERE LUKUID = 3

	SELECT *
	FROM @TAULU
	WHERE KAYTETTY = 0

		SELECT COUNT(1) AS VAPAAT
		FROM @TAULU
		WHERE KAYTETTY = 0

	WHILE 1=1
	BEGIN
		INSERT INTO @TAULU VALUES (@I,0)
		SET @I +=1
		IF @I >1000
		BEGIN
			BREAK
		END
	END

BEGIN
		SET @VAPAAT=(	SELECT COUNT(1) AS VAPAAT
		FROM @TAULU
		WHERE KAYTETTY = 0)
		PRINT @VAPAAT		
END

END