CREATE SCHEMA PANKKI AUTHORIZATION DBO


CREATE TABLE PANKKI.asiakas(
ID BIGINT IDENTITY(1,1) NOT NULL
CONSTRAINT PK_ASIAKAS PRIMARY KEY (ID)
)

CREATE TABLE PANKKI.YRITYS(
ID BIGINT NOT NULL,
NIMI VARCHAR(200) NOT NULL,
YTUNNUS CHAR (9),
ASIAKASID BIGINT NOT NULL
CONSTRAINT PK_YRITYS PRIMARY KEY(ID),
CONSTRAINT FK_YRITYS_ASIAKAS FOREIGN KEY (ASIAKASID) REFERENCES PANKKI.ASIAKAS,
CONSTRAINT MUOTO_YTUNUNS CHECK ((YTUNNUS LIKE ('_______‐_')))

)
DROP TABLE PANKKI.HENKILO
CREATE TABLE PANKKI.HENKILO(
ID BIGINT NOT NULL,
SUKUNIMI VARCHAR(200) NOT NULL,
ETUNIMI VARCHAR (200) NOT NULL,
HENKILOTUNNUS CHAR(11),
ASIAKASID BIGINT NOT NULL
CONSTRAINT PK_HENKILO PRIMARY KEY(ID),
CONSTRAINT FK_HENKILO_ASIAKAS FOREIGN KEY (ASIAKASID) REFERENCES  PANKKI.ASIAKAS,
CONSTRAINT MUOTO_HTUNNUS CHECK ((HENKILOTUNNUS LIKE ('______-____') OR HENKILOTUNNUS LIKE ('______A____')))

)

CREATE TABLE PANKKI.TILITAPAHTUMA(
ID BIGINT IDENTITY(1,1) NOT NULL,
TAPAHTUMAPAIVA DATETIME DEFAULT CURRENT_TIMESTAMP,
MAARA DECIMAL(11,2),
TYYPPI CHAR(1),
TILICD VARCHAR(20) NOT NULL
CONSTRAINT PK_TILITAPAHTUMA PRIMARY KEY(ID),
CONSTRAINT TYYPPI_TAPAHTUMA CHECK ((TYYPPI IN ( 'P', 'O', 'I', 'D'))),
)

CREATE TABLE PANKKI.TILI(
CD VARCHAR(20) NOT NULL,
SALDO DECIMAL(11,2)DEFAULT 0
, PERUSTAMISPVM DATE DEFAULT CURRENT_TIMESTAMP,
LUOTTORAJA DECIMAL(11,2)DEFAULT 0,
TILA CHAR(1) DEFAULT 'K',
ASIAKASID BIGINT NOT NULL
CONSTRAINT PK_TILI PRIMARY KEY(CD),
CONSTRAINT FK_TILI_ASIAKAS FOREIGN KEY(ASIAKASID) REFERENCES PANKKI.asiakas,
CONSTRAINT POS_SALDO_TILI CHECK((LUOTTORAJA IS NULL AND SALDO   >= 0) OR (LUOTTORAJA IS NOT NULL AND SALDO >= LUOTTORAJA)),
CONSTRAINT TILA_TILI CHECK ((TILA IN ('K','E')))

)


CREATE VIEW PANKKI.ASIAKASTILI AS
SELECT C.CD, C.SALDO,CONCAT(B.ETUNIMI , ' ' , B.SUKUNIMI) AS NIMI,B.HENKILOTUNNUS AS TUNNUS
FROM PANKKI.ASIAKAS AS A 
JOIN PANKKI.HENKILO AS B ON B.ASIAKASID = A.ID
JOIN PANKKI.TILI AS C ON C.ASIAKASID = A.ID
UNION
SELECT C.CD,C.SALDO, B.NIMI, B.YTUNNUS AS TUNNUS
FROM PANKKI.ASIAKAS AS A JOIN PANKKI.YRITYS AS B ON B.ASIAKASID = A.ID
JOIN PANKKI.TILI AS C ON C.ASIAKASID = A.ID


